//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTPServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompositeItem
    {
        public string ItemId { get; set; }
        public string ItemPath { get; set; }
        public string ParentPath { get; set; }
        public string ItemName { get; set; }
        public string UserId { get; set; }
        public string ItemType { get; set; }
    
        public virtual User User { get; set; }
    }
}
